version: 2.1
jobs:
  build:
    docker:
      # below workaround is necessary to avoid below error on Maven
      # Error: Could not find or load main class org.apache.maven.surefire.booter.ForkedBooter
      # https://discuss.circleci.com/t/circleci-build-failure-on-openjdk-image/26104/9
      - image: circleci/openjdk:8u171-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn -q clean checkstyle:check scalastyle:check package

      - when:
          condition: true
          steps:
            - store_artifacts:
                path: ~/repo/target/scalastyle-output.xml
                destination: scalastyle-output.xml

            - store_artifacts:
                path: ~/repo/target/unit-tests.log
                destination: unit-tests.log
